- id: translation-checker
  name: Translation Checker
  description: This hook checks for missing translations in TypeScript and JavaScript files.
  entry: translation_checker  # The entry point script
  language: rust
  files: \.(js|jsx|ts|tsx)$
